# Generated by Django 4.2.1 on 2023-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
