# Generated by Django 3.2.11 on 2023-06-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20230605_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_image',
        ),
    ]
