# Generated by Django 3.2.11 on 2023-06-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_product_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='start_date',
        ),
    ]
